trigger:
  - main

pool:
  name: Default
  vmImage: ubuntu-latest

variables:
  kubernetesServiceConnection: $(KUBERNETES_SERVICE_CONNECTION)
  kubernetesNamespace: default
  system.debug: true

steps:
  - task: HelmDeploy@0
    displayName: Add Helm repo
    inputs:
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: $(kubernetesServiceConnection)
      namespace: $(kubernetesNamespace)
      command: repo
      arguments: add traefik https://traefik.github.io/charts

  - task: HelmDeploy@0
    displayName: Deploy Traefik
    inputs:
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: $(kubernetesServiceConnection)
      namespace: $(kubernetesNamespace)
      command: upgrade
      chartType: Name
      chartName: traefik/traefik
      releaseName: traefik
      arguments: --install --values values.yaml

